language: c

script: asdf plugin-test skaffold https://github.com/virtualstaticvoid/asdf-skaffold.git "skaffold version --client"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - jq

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install jq; fi
